<?php
/* Hojas ES. El español va a PYME ESPAÑOLA —«a medida», «para empresas», que
 * es la forma real de la query según la SERP medida el 2-sep-2026— y no es la
 * traducción del inglés: los casos se reencuadran POR PROBLEMA, no por país.
 * Un industrial de Alicante no compra un ERP porque le enseñes villas en Bali;
 * le compra porque reconoce su problema. La prueba se cuenta igual de real,
 * pero entra por donde duele. */

$HOJAS_ES = [

'software-de-gestion-a-medida' => [
  'lang'=>'es','url'=>'/es/servicios/software-de-gestion-a-medida','codigo'=>'B01','eje'=>'BUILD',
  'title'=>'Software de gestión a medida para empresas — AxisWorks',
  'desc'=>'Herramientas internas escritas para cómo trabaja tu empresa: contratos, facturas, inventario, permisos y portal de cliente, todo leyendo un solo dato. Estudio de dos personas.',
  'eyebrow'=>'HOJA B01 — BUILD',
  'h1'=>'Software de gestión a medida para empresas',
  'lead'=>'Casi ninguna empresa necesita otra plataforma a la que adaptarse. Necesita que las veinte cosas que hace cada día dejen de vivir en hojas de cálculo, hilos de WhatsApp y la memoria de una persona.',
  'spec'=>[
    'Una suite interna no es una plantilla con tu logo. Está escrita en tu vocabulario, imprime tus documentos y aplica tus permisos — que son justo las tres cosas que el software enlatado te obliga a rodear.',
    'Diseñamos contra un fallo concreto: <b>el mismo dato viviendo en dos sitios</b>. Es el error más caro que conocemos y nunca parece un error. Un precio que vive en el contrato y otra vez en la pantalla de operaciones se separa, y un día algo se factura al doble. No es hipotético: nos ha pasado y por eso cada herramienta que construimos lee una sola fuente por dato, y añadir una herramienta nueva nunca significa copiar una lista.',
    'El portal de cliente y las integraciones están en esta hoja y no en la suya porque en la práctica no son productos distintos: el portal es el mismo dato con otra puerta, y las integraciones son lo que evita que tu equipo lo reescriba a mano.',
  ],
  'scope'=>[
    ['Modelo de datos','Una fuente por dato. Precios, fechas y nombres se escriben una vez y se leen en todas partes.'],
    ['Documentos','Contratos, facturas y recibos generados en PDF desde el propio registro — no tecleados dos veces.'],
    ['Roles y permisos','Por usuario y por herramienta. Lo que alguien no puede hacer, no lo ve.'],
    ['Portal de cliente','<span id="portal"></span>Una puerta para quien está fuera de la empresa, sobre el mismo dato y con sus propias reglas.'],
    ['Integraciones','<span id="integraciones"></span>Cobros, calendarios, hojas de cálculo, mensajería — allí donde el dato ya vive.'],
    ['Idiomas','La interfaz en tantos idiomas como hable el equipo de verdad.'],
    ['Entrega','Código, base de datos y despliegue. Escrito para que lo lea el siguiente desarrollador.'],
  ],
  'caso'=>[
    'img'=>'work-lawang.jpg','alt'=>'Suite interna de una promotora inmobiliaria',
    'titulo'=>'Una promotora inmobiliaria que vendía sobre plano en carpetas',
    'texto'=>'Contratos con firma digital remota, facturas y recibos, avance de obra, compradores, calendario de vencimientos, catálogo de unidades, documentación y un portal donde cada comprador ve sus propios contratos y pagos. Once herramientas bajo un solo menú, una cáscara compartida, un solo acceso. Una persona se da de alta en un único sitio y todas las demás herramientas la leen de ahí. (Opera en Indonesia; el problema es el mismo en Murcia.)',
    'cifras'=>[['11','herramientas, un menú'],['2','idiomas de interfaz'],['1','alta por persona']],
  ],
  'faq'=>[
    ['¿Esto es un ERP?','A veces sustituye a uno, más a menudo convive con él. Un ERP enlatado es bueno en lo que todas las empresas hacen igual —contabilidad, nóminas— y malo justo en la parte que te hace diferente, que suele ser donde están el dinero y los errores. Esa parte es la que construimos.'],
    ['Ya usamos hojas de cálculo y funcionan. ¿Por qué cambiar?','Las hojas funcionan hasta que las editan dos personas, hasta que un número tiene que salir en un documento, o hasta que alguien se va. La señal no es que la hoja vaya lenta: es que alguien está reescribiendo a mano.'],
    ['¿Podéis construir sobre lo que ya tenemos?','Sí, y suele salir más barato. Si el dato ya vive en un sistema con API, lo leemos en vez de migrarlo.'],
    ['¿Cuánto se tarda?','Depende por completo del alcance, así que no damos un número antes de entender el tuyo. Cuéntanos qué hace el equipo hoy y te devolvemos alcance y precio.'],
    ['¿Quién lo usa, solo la oficina?','Quien tenga un rol. En el caso de arriba lo usan el equipo de la promotora, la parte de obra y los propios compradores, cada uno por su puerta.'],
  ],
  'asunto'=>'Software de gestión a medida — /es/servicios/software-de-gestion-a-medida',
],

'crm-a-medida' => [
  'lang'=>'es','url'=>'/es/servicios/crm-a-medida','codigo'=>'B02','eje'=>'BUILD',
  'title'=>'Desarrollo de CRM a medida para tu empresa — AxisWorks',
  'desc'=>'Un CRM con la forma de tu proceso de venta: los leads entran solos desde el canal por el que llegan de verdad, con reservas, cobros y seguimiento. Desarrollo y despliegue propios.',
  'eyebrow'=>'HOJA B02 — BUILD',
  'h1'=>'Desarrollo de CRM a medida para tu empresa',
  'lead'=>'Un CRM genérico te obliga a describir tu negocio con las palabras de otro. Si tus leads entran por WhatsApp y lo que vendes es una reserva, una etapa llamada «Oportunidad» no le sirve a nadie.',
  'spec'=>[
    'Un CRM a medida se justifica cuando el estándar se pelea en vez de usarse: cuando el equipo mantiene una hoja de cálculo paralela al lado, o cuando la mitad de los campos están vacíos porque no aplican.',
    'Lo que hace que un CRM viva o muera no es la vista de embudo. Es si los leads entran <b>solos</b>, desde el canal por el que llegan realmente. Un CRM al que hay que copiar los leads a mano es una hoja de cálculo con una interfaz más lenta.',
    'Por eso construimos primero la entrada —formulario web, WhatsApp, plataforma de anuncios, teléfono— y el embudo después. Y lo atamos al dinero: qué se presupuestó, qué se cobró y qué queda pendiente.',
  ],
  'scope'=>[
    ['Entrada','Leads capturados desde los canales que ya usas, con su origen pegado.'],
    ['Embudo','Etapas con el nombre que les da tu equipo, no un funnel genérico.'],
    ['Reservas o pedidos','Lo que vendes de verdad, con sus fechas, sus unidades y su precio.'],
    ['Cobros','Señales y pendientes, unidos al registro y a la pasarela cuando la hay.'],
    ['Seguimiento','Avisos que saltan el día que dijo el cliente, no cuando alguien se acuerda.'],
    ['Equipo','Roles, asignación e histórico visible de quién hizo qué.'],
    ['Informes','Los tres números con los que de verdad se pilota, no un panel que no abre nadie.'],
  ],
  'caso'=>[
    'img'=>'work-sumba.jpg','alt'=>'CRM de flota y reservas',
    'titulo'=>'Un alquiler de vehículos que perdía la reserva en la segunda consulta',
    'texto'=>'CRM de flota y disponibilidad, reservas con entrega a domicilio, cobros por pasarela local y equipo editable. Tres idiomas de interfaz, incluido el del país donde trabaja el equipo — porque quien lo usa cada día no es quien lo encargó.',
    'cifras'=>[['3','idiomas de interfaz'],['2','webs públicas que alimenta'],['1','registro por reserva, de punta a punta']],
  ],
  'faq'=>[
    ['¿Por qué no HubSpot o Pipedrive?','Si un CRM estándar encaja, úsalo: sale más barato que cualquier cosa que construyamos. Ven cuando no encaja — cuando lo que vendes no es un «trato», cuando tus leads llegan por un sitio que el CRM no sabe leer, o cuando el coste por usuario ya ha superado al de tener el tuyo.'],
    ['¿Puede leer los leads de WhatsApp?','Sí. Es la entrada que más construimos y la que normalmente justifica el proyecto ella sola.'],
    ['¿Gestiona cobros?','Los registra, y donde hay pasarela la conectamos para que el registro se actualice solo en vez de que alguien marque una casilla.'],
    ['¿Podemos migrar los datos que ya tenemos?','Normalmente sí. La respuesta honesta depende del estado en que estén: un export limpio es una tarde, diez años de hojas inconsistentes son un proyecto aparte.'],
    ['¿Cuánto cuesta?','Cada proyecto se presupuesta por su alcance. Si quieres la respuesta larga, está en <a href="/es/cuanto-cuesta-un-software-a-medida">cuánto cuesta un software a medida</a>.'],
  ],
  'asunto'=>'CRM a medida — /es/servicios/crm-a-medida',
],

'chatbot-whatsapp-ia' => [
  'lang'=>'es','url'=>'/es/servicios/chatbot-whatsapp-ia','codigo'=>'B03','eje'=>'BUILD',
  'title'=>'Chatbot de WhatsApp con IA para empresas — AxisWorks',
  'desc'=>'Bots sobre la API oficial de WhatsApp Business que contestan con tu voz, reservan en un calendario real, mandan enlaces de pago y saben cuándo pasar a un humano.',
  'eyebrow'=>'HOJA B03 — BUILD',
  'h1'=>'Chatbot de WhatsApp con IA para empresas',
  'lead'=>'El objetivo no es un bot que conteste al instante y perfecto. Es un bot que cierre la cita, mande el enlace de pago y sepa quitarse de en medio a tiempo.',
  'spec'=>[
    'Construimos sobre la API oficial de WhatsApp Business, no sobre un puente no oficial. Esa decisión cuesta más al principio y es la razón de que el número no acabe baneado.',
    'Al bot se le da el negocio, no un guion: precios, disponibilidad, qué se ofrece y qué no. Contesta en el idioma del cliente y pasa la conversación a una persona en el momento en que debe — un bot que improvisa sobre dinero es un pasivo, y los nuestros están construidos para no poder hacerlo.',
    'Dos cosas que aprendimos caras y hoy van de serie. <b>La latencia es lo que delata al bot</b>: una respuesta que llega en 400 milisegundos se lee como una máquina por buenas que sean las palabras. Y un bot nunca puede mandarle a un cliente real un mensaje con un hueco sin rellenar — eso es una regla escrita en el código, no una nota en el prompt.',
  ],
  'scope'=>[
    ['Canal','API oficial de WhatsApp Business, con el número y las plantillas dados de alta como toca.'],
    ['Conocimiento','Tus precios, tu disponibilidad, tus reglas — una sola fuente, actualizable sin redesplegar.'],
    ['Reservas','Escribe en un calendario real, no en un formulario que el equipo vuelve a teclear.'],
    ['Cobros','Manda un enlace de pago vivo y sabe cuándo se ha pagado.'],
    ['Traspaso','Una línea que el bot no cruza, y un paso limpio a una persona cuando llega a ella.'],
    ['Idiomas','Contesta en el idioma en que se le escribe, incluidos los que habla tu equipo.'],
    ['Visibilidad','Todas las conversaciones legibles por ti, con qué dijo el bot y por qué.'],
  ],
  'caso'=>[
    'img'=>'work-balimoto.jpg','alt'=>'Bot de WhatsApp en producción',
    'titulo'=>'Un operador turístico que contestaba a mano el mismo mensaje veinte veces al día',
    'texto'=>'El bot responde sobre rutas y precios, reserva citas directamente en Google Calendar, manda enlaces de pago de Stripe y se agenda su propio seguimiento cuando un lead dice «me lo reviso». Llega al equipo por el mismo panel donde están los leads.',
    'cifras'=>[['24/7','contestando, en producción'],['1','red de seguridad que frena el envío'],['1','línea de traspaso, escrita en código']],
  ],
  'faq'=>[
    ['¿Nos van a banear el número?','No si está construido sobre la API oficial de Business con plantillas dadas de alta, que es como los hacemos. Los que banean números son los puentes no oficiales, y son más baratos exactamente por eso.'],
    ['¿Puede usar nuestro número actual de WhatsApp?','Normalmente sí, por la vía oficial de migración o coexistencia. Es un trámite con Meta más que un interruptor, y cuánto tarda lo deciden ellos, no nosotros.'],
    ['¿Qué impide que se invente un precio?','Lee los precios de una sola fuente y no puede contestar fuera de ella. Cuando una pregunta toca dinero que no tiene, pasa a una persona.'],
    ['¿Puede entrar un humano a mitad de conversación?','Sí, y ese es el punto. El bot está para quitar el 80% repetitivo, no para ponerse entre tú y un cliente que ya quiere comprar.'],
    ['¿Funciona en varios idiomas?','Sí. Los nuestros funcionan en español, inglés e indonesio según el proyecto.'],
  ],
  'asunto'=>'Chatbot de WhatsApp con IA — /es/servicios/chatbot-whatsapp-ia',
],

'automatizacion-de-procesos' => [
  'lang'=>'es','url'=>'/es/servicios/automatizacion-de-procesos','codigo'=>'B04','eje'=>'BUILD',
  'title'=>'Automatización de procesos con IA y agentes — AxisWorks',
  'desc'=>'Automatizaciones y vigilantes autónomos que revisan tu negocio a todas horas, te avisan en directo y tienen permiso para frenar — nunca para gastar. En producción hoy.',
  'eyebrow'=>'HOJA B04 — BUILD',
  'h1'=>'Automatización de procesos con IA y agentes',
  'lead'=>'La automatización que merece la pena no es la que ahorra diez minutos. Es la que se da cuenta, a las tres de la mañana, de que llevas tres días gastando sin recibir nada.',
  'spec'=>[
    'En esta hoja hay dos cosas. Las <b>automatizaciones</b> quitan un paso que una persona repite: un documento que se genera solo, un registro que se actualiza solo, un informe que llega sin pedirlo. Los <b>vigilantes</b> son otra cosa: un proceso que vive dentro de algo que ya corre 24/7, revisa el estado del negocio cada cierto tiempo y te escribe en directo cuando algo va mal.',
    'La regla que hace que un vigilante sea fiable es la <b>autonomía asimétrica</b>, y la impone la forma del código, no una instrucción. Puede pausar, frenar y proteger por su cuenta. Nunca puede gastar, nunca crear y nunca escribir a un cliente real. Esa asimetría es todo el diseño.',
    'No construimos un vigilante para un problema que nadie ha sufrido todavía. Los dos que corren hoy salieron de un incidente: un negocio estuvo tres días gastando en anuncios con cero leads sin que nadie se enterara; otro venía de un cobro duplicado y de un rediseño que pasó un QA automático estando mal.',
  ],
  'scope'=>[
    ['Qué vigila','Lo concreto que dolió la última vez — gasto, silencio, una cola, un número que no debería moverse.'],
    ['Cadencia','Un intervalo que va al ritmo real de lo que cambia, no al más rápido posible.'],
    ['Aviso','Canal directo a una persona. Un bot por negocio, nunca un grupo.'],
    ['Lo que puede','Pausar, frenar, proteger. Escrito en el código como lo que *puede* hacer, no como lo que *debería*.'],
    ['Prohibido por diseño','Gastar, crear y escribir a tus clientes. No es configurable.'],
    ['Estado','En base de datos, nunca en disco: un redespliegue no puede hacerle olvidar lo que ya hizo.'],
    ['Auditoría','Cada acción queda registrada, y todas son reversibles por ti.'],
  ],
  'caso'=>[
    'img'=>'work-lawang.jpg','alt'=>'Vigilantes autónomos en producción',
    'titulo'=>'Dos vigilantes, dos negocios, los dos en producción',
    'texto'=>'Uno revisa gasto y leads cada cuatro horas: puede pausar un conjunto en sequía y repartir presupuesto diario dentro de un tope mensual que fija el dueño, y no puede salirse de esa jaula. El otro lee conversaciones vivas de leads cada media hora y pausa anuncios sin retorno. Los dos avisan por un canal privado de Telegram; ninguno puede crear una campaña ni escribir a un cliente.',
    'cifras'=>[['4h / 30min','intervalos en producción'],['0','acciones que gasten fuera del tope'],['1:1','canal de aviso, nunca un grupo']],
  ],
  'faq'=>[
    ['¿Esto es n8n o Zapier?','Esos son buenos uniendo dos servicios que ya tienen botones el uno para el otro. Nosotros escribimos los que necesitan criterio, los que no pueden romperse en silencio y los que tienen que recordar su estado tras un redespliegue.'],
    ['¿Actuaría sin preguntarnos?','Solo en el sentido de frenar algo, y solo dentro de los límites que pongas tú. No puede gastar, ni crear, ni contactar con nadie. Es una propiedad del código, no un ajuste.'],
    ['¿Dónde se ejecuta?','Dentro de un servicio que ya esté corriendo para tu negocio a todas horas. Si no hay ninguno, lo primero es construirlo: una automatización que depende de que alguien abra el portátil no vigila nada.'],
    ['¿Y si se equivoca?','Cada acción queda registrada y es reversible, y el aviso te llega antes de que te hubieras dado cuenta tú. El fallo de tener un vigilante es una falsa alarma; el de no tenerlo son tres días de gasto.'],
    ['¿Usa IA para decidir?','Donde de verdad hace falta criterio, sí — por ejemplo para leer si una conversación se ha torcido. El resto es código determinista, porque la mayoría de lo que vigila no necesita un modelo y es más fiable sin él.'],
  ],
  'asunto'=>'Automatización de procesos — /es/servicios/automatizacion-de-procesos',
],

'meta-ads' => [
  'lang'=>'es','url'=>'/es/servicios/meta-ads','codigo'=>'G01','eje'=>'GROW',
  'title'=>'Agencia de Meta Ads: embudos de venta en Facebook e Instagram — AxisWorks',
  'desc'=>'Campañas, creatividades y la fontanería de detrás: que el lead llegue a tu CRM con su origen pegado en vez de morir en una bandeja de entrada.',
  'eyebrow'=>'HOJA G01 — GROW',
  'h1'=>'Agencia de Meta Ads: embudos de venta en Facebook e Instagram',
  'lead'=>'Casi ninguna cuenta rinde mal por la segmentación. Rinde mal porque nadie sabe decir qué anuncio produjo al cliente.',
  'spec'=>[
    'Llevamos la línea entera, no solo la compra de medios: estructura de campañas, la creatividad que va dentro y la fontanería que lleva al lead desde el anuncio hasta un sitio donde una persona lo va a contestar. Las tres son el mismo trabajo — una creatividad que convierte a un formulario que nadie lee no es una victoria.',
    'Como además construimos el software, podemos cerrar el círculo que casi todas las agencias dejan abierto: el lead aterriza en el CRM con su campaña pegada, así que el informe habla de facturación y no de clics.',
    'Y lo que corre, se vigila. Un conjunto que deja de producir lo caza el mismo tipo de vigilante de la <a href="/es/servicios/automatizacion-de-procesos">hoja B04</a> — revisado cada pocas horas, pausado si está en sequía, dentro de un tope mensual que pones tú. Nadie descubre una semana tirada a fin de mes.',
  ],
  'scope'=>[
    ['Estructura','Campañas y conjuntos montados para que los resultados se puedan leer, no para que queden ordenados.'],
    ['Creatividades','Hechas para el emplazamiento y la pantalla donde se van a ver — casi todo se mira a tamaño miniatura.'],
    ['Aterrizaje','A dónde va el clic y si se gana la consulta.'],
    ['Medición','Origen pegado al lead, hasta la venta.'],
    ['Contenido y redes','<span id="redes"></span>El lado orgánico que abarata el de pago: qué publica la cuenta y con qué voz.'],
    ['Vigilancia','Gasto y leads revisados por intervalos, con permiso para pausar y para nada más.'],
    ['Informe','Qué costó, qué produjo y qué vamos a cambiar.'],
  ],
  'caso'=>[
    'img'=>'work-balimoto.jpg','alt'=>'Embudos de Meta Ads en producción',
    'titulo'=>'Dos cuentas vivas, dos productos opuestos',
    'texto'=>'Una vende rutas en moto a viajeros y la otra villas a inversores: misma disciplina, embudos contrarios. Las dos con creatividades hechas para móvil, las dos alimentando un CRM que sabe de dónde vino cada lead, y las dos vigiladas por un proceso que puede pausar un conjunto en sequía por su cuenta pero nunca subir el gasto por encima del tope mensual del dueño.',
    'cifras'=>[['2','cuentas vivas en producción'],['1','tope mensual, nunca superado'],['0','presupuestos subidos sin el dueño']],
  ],
  'faq'=>[
    ['¿Necesitáis acceso a nuestra cuenta publicitaria?','Sí, como socios en tu Business Manager. La propiedad de la cuenta, del píxel y de los públicos sigue siendo tuya, siempre.'],
    ['¿Quién paga la inversión publicitaria?','Tú, directamente a Meta. Nunca tenemos tu presupuesto de anuncios en nuestras manos.'],
    ['¿Hacéis también las creatividades?','Sí. Ahí suele estar la diferencia: la misma oferta con una creatividad pensada para un lienzo de 1080px que se ve a tamaño miniatura rinde de forma muy distinta a una diseñada mirando un monitor.'],
    ['¿Podéis conectar los anuncios con nuestro CRM?','Sí, y es la parte en la que insistiríamos. Sin eso no hay manera de saber qué campaña produjo un cliente en vez de un clic.'],
    ['¿Cuál es el presupuesto mínimo?','Depende del mercado y del producto, así que no vamos a inventarnos una cifra. Cuéntanos qué vendes y qué estás gastando, y te decimos honestamente si podemos mejorarlo.'],
  ],
  'asunto'=>'Meta Ads — /es/servicios/meta-ads',
],

'cuanto-cuesta-un-software-a-medida' => [
  'lang'=>'es','url'=>'/es/cuanto-cuesta-un-software-a-medida','codigo'=>'DOC','eje'=>'',
  'title'=>'Cuánto cuesta un software a medida (y qué mueve el precio) — AxisWorks',
  'desc'=>'Qué encarece de verdad un desarrollo a medida, qué lo abarata, y cómo decidir entre comprar una herramienta enlatada o construir la tuya. Sin cifras inventadas.',
  'eyebrow'=>'DOCUMENTO — ANTES DE PEDIR PRESUPUESTO',
  'h1'=>'Cuánto cuesta un software a medida (y qué mueve el precio)',
  'lead'=>'Nadie puede darte una cifra sin saber qué vas a construir, y quien te la da en la primera llamada te la va a corregir en la tercera. Lo que sí se puede explicar con honestidad es qué mueve la aguja.',
  'spec'=>[
    'No publicamos tarifa. No es opacidad: es que el mismo encargo —«un CRM»— puede ser dos semanas o seis meses según cinco cosas que casi nunca están en el brief inicial. Publicar un «desde X€» solo sirve para que el número se quede corto y el proyecto empiece con una conversación incómoda.',
    'Lo que sigue es lo que de verdad mueve el precio, en orden de impacto. Si al leerlo reconoces tu caso, ya sabes por qué el presupuesto que te den va a salir alto o bajo — y qué puedes cambiar tú para bajarlo.',
    'Y la pregunta anterior a todas: <b>¿de verdad hay que construirlo?</b> Si una herramienta enlatada cubre lo tuyo, cómprala; sale más barata que cualquier cosa que construyamos y lo decimos aunque nos deje sin proyecto. Construir se justifica cuando el estándar se pelea en vez de usarse: cuando hay una hoja de cálculo paralela al lado, cuando la mitad de los campos no aplican, o cuando el coste por usuario ya supera al de tener el tuyo.',
  ],
  'scope'=>[
    ['Nº de integraciones','Lo que más encarece, y casi nadie lo cuenta al pedir precio. Cada sistema ajeno con el que hay que hablar es su propia autenticación, sus propios errores y sus propias sorpresas.'],
    ['Estado de tus datos','Un export limpio es una tarde. Diez años de hojas inconsistentes, con el mismo cliente escrito de cuatro formas, es un proyecto aparte — y hay que hacerlo antes.'],
    ['Documentos','Si el sistema tiene que <i>imprimir</i> —contratos, facturas, certificados— multiplica. Un PDF que debe ser correcto y legalmente utilizable no es una pantalla más.'],
    ['Roles y permisos','Dos tipos de usuario es una tarde. Siete, con cosas que unos ven y otros no, es una capa de arquitectura.'],
    ['Idiomas','Uno es gratis. Dos ya obliga a decidir qué manda cuando los textos no coinciden, que es una decisión de negocio y no de software.'],
    ['Quién decide','El factor oculto. Un interlocutor que puede decidir acelera el proyecto más que cualquier tecnología; un comité lo dobla.'],
    ['Lo que NO lo mueve','El número de pantallas. Es lo que todo el mundo cuenta y lo que menos correlaciona con el trabajo real.'],
  ],
  'caso'=>[
    'img'=>'work-ids.jpg','alt'=>'Portal de clientes con login, roles y documentos',
    'titulo'=>'Dos proyectos, la misma frase de partida',
    'texto'=>'«Queremos un portal para nuestros clientes.» Uno acabó siendo login, roles, comunidades y documentos por categorías: acotado y previsible. El otro, la misma frase, arrastraba contratos, firmas, cobros y obra — y era diez veces el trabajo. La diferencia no estaba en el número de pantallas; estaba en cuántos documentos tenía que emitir y cuántos sistemas ajenos tenía que leer.',
    'cifras'=>[['5','factores que mueven el precio'],['1','que casi nadie cuenta: las integraciones'],['0','tarifas publicadas']],
  ],
  'faq'=>[
    ['¿Por qué no publicáis precios?','Porque el mismo encargo puede costar diez veces más según las cinco cosas de arriba, y un «desde X€» que luego no se cumple es peor que no decir nada. Cuéntanos el alcance y te devolvemos alcance y precio, por escrito.'],
    ['¿Cómo puedo abaratar mi proyecto?','Tres palancas reales: reducir integraciones a las imprescindibles de la primera versión, limpiar tus datos antes de empezar, y poner a una sola persona con capacidad de decidir.'],
    ['¿Sale más barato una plantilla o un no-code?','Al principio, casi siempre sí, y es una respuesta legítima. Deja de serlo cuando el negocio depende de algo que la plantilla no hace, o cuando la cuota mensual por usuario ya pesa más que el desarrollo.'],
    ['¿Se paga todo de golpe?','No. Un proyecto se trocea en entregas verificables y cada una se cierra antes de empezar la siguiente, para que en cualquier punto tengas algo que funciona.'],
    ['¿Qué pasa si el alcance cambia a mitad?','Cambia el presupuesto, y se dice cuando ocurre y no al final. Es la razón de trocear: un cambio de alcance en la entrega 3 no obliga a renegociar las siete.'],
  ],
  'asunto'=>'Presupuesto — /es/cuanto-cuesta-un-software-a-medida',
],


'portal-de-clientes' => [
  'lang'=>'es','url'=>'/es/servicios/portal-de-clientes','codigo'=>'B05','eje'=>'BUILD',
  'title'=>'Portal de clientes a medida para empresas — AxisWorks',
  'desc'=>'Un área privada donde cada cliente ve su expediente: contratos, pagos y documentos, leídos de los mismos datos con los que trabaja tu equipo. Nadie ve lo de otro.',
  'eyebrow'=>'HOJA B05 — BUILD',
  'h1'=>'Portal de clientes a medida',
  'lead'=>'Cada «¿me reenvías el contrato?» es un mensaje que alguien de tu equipo tiene que contestar. Un portal lo contesta antes de que lo pregunten.',
  'spec'=>[
    'Un portal de clientes no es un segundo sistema. Son los mismos datos que tu equipo ya lleva, vistos por una puerta con sus propias reglas: el cliente ve sus contratos, sus pagos y sus documentos, y nada que sea de otro. Si el portal guarda su propia copia del expediente, en un mes no cuadran, y el primero en notarlo es el cliente.',
    'Lo que decide si un portal se usa no es el diseño, es <b>entrar</b>. Lo aprendimos en un proyecto en marcha: diecinueve accesos dados a mano y uno solo estrenado. El cuello de botella era el correo de invitación, no el cliente. Ahora el acceso funciona al revés: si el cliente tiene ficha y al menos un contrato, entra con su propio correo, y la regla se comprueba en el momento en que llega.',
    'Los permisos se hacen cumplir en la base de datos, no en la pantalla. Esconder un botón no es seguridad: un cliente que no debe ver otro expediente no puede leerlo ni escribiendo la dirección a mano.',
  ],
  'scope'=>[
    ['Acceso','Entrada con su correo, concedida por una regla —ficha más contrato— y no por una invitación manual.'],
    ['El expediente','Contratos, calendario de pagos, recibos y documentos, leídos en vivo del sistema de tu equipo.'],
    ['Aislamiento','Reglas por fila en la base de datos: cada cliente solo puede leer lo suyo.'],
    ['Documentos','PDF firmados y recibos descargables en cuanto existen.'],
    ['Pagos','Qué debe, qué ha pagado y cuándo, del mismo registro con el que factura la oficina.'],
    ['Categorías','Documentos ordenados por categorías que editáis vosotros.'],
    ['Registro','Quién entró y qué abrió, guardado en tu lado.'],
  ],
  'caso'=>[
    'img'=>'work-ids.jpg','alt'=>'IDS Fincas — portal de clientes',
    'titulo'=>'IDS Fincas — administración de fincas en Murcia',
    'texto'=>'Un portal para una administración de fincas: cada vecino entra y ve los documentos de sus comunidades —puede pertenecer a varias—, ordenados en categorías que la administración edita. Sin autorregistro: el alta llega por un enlace para crear la contraseña, y las descargas comprueban en el servidor que el documento es suyo. El mismo patrón corre para los compradores de una promotora, con contratos y pagos en vez de actas.',
    'cifras'=>[['N:N','vecinos y comunidades'],['0','documentos que se abren sin permiso'],['1','panel de administración']],
  ],
  'faq'=>[
    ['¿Nuestros clientes tienen que instalar algo?','No. Es una página web que funciona en el móvil. Entran con su correo.'],
    ['¿Puede un cliente ver el expediente de otro?','No, y no porque el botón esté escondido. La base de datos se niega a devolver lo que no es suyo, escriba la dirección que escriba.'],
    ['¿Sustituye a nuestro programa de gestión?','No, es una puerta a él. Y si aún no tenéis uno, el portal suele ser el motivo para hacerlo: mira la <a href="/es/servicios/software-de-gestion-a-medida">hoja B01</a>.'],
    ['¿Pueden los clientes subir documentos?','Sí, donde tenga sentido: una copia firmada, un justificante de pago. Lo que suben cae en el mismo expediente con el que trabaja el equipo.'],
    ['¿Cuánto cuesta?','Se presupuesta por alcance, y sale mucho más barato si los datos internos ya existen. Cuéntanos qué es lo que más te piden tus clientes.'],
  ],
  'asunto'=>'Portal de clientes — /es/servicios/portal-de-clientes',
],

'integraciones-y-datos' => [
  'lang'=>'es','url'=>'/es/servicios/integraciones-y-datos','codigo'=>'B06','eje'=>'BUILD',
  'title'=>'Integración de sistemas y datos para empresas — AxisWorks',
  'desc'=>'Conectamos las herramientas que ya pagas para que nadie vuelva a teclear: leads de anuncios al CRM, cobros al expediente, reservas al calendario. Si falla, avisa.',
  'eyebrow'=>'HOJA B06 — BUILD',
  'h1'=>'Integración de sistemas y datos',
  'lead'=>'Lo caro de tener seis programas no son las licencias. Es la persona que pasa datos de uno a otro, y el día que los pasa mal.',
  'spec'=>[
    'Una integración merece la pena cuando una persona está haciendo de cable entre dos sistemas. Entra un lead en la plataforma de anuncios y alguien lo copia al CRM; llega una transferencia y alguien marca una casilla; se hace una reserva y alguien la apunta en el calendario. Cada uno de esos pasos es un sitio por donde se pierden datos sin que nadie se entere.',
    'La regla con la que trabajamos es que <b>cada dato tiene un dueño</b>. Si dos sistemas guardan el precio, la fecha o el nombre del cliente, la integración decide cuál manda y el otro solo lee. Copiar en las dos direcciones es la forma de acabar con dos sistemas que no coinciden y nadie sabe cuál tiene razón.',
    'Y una integración tiene que <b>fallar haciendo ruido</b>. Las peores son las que dejan de funcionar un martes y nadie se entera hasta fin de mes. Las nuestras registran lo que han movido y, cuando una llamada falla, se lo dicen a una persona, no a un registro que nadie lee.',
  ],
  'scope'=>[
    ['Mapa','Qué vive dónde hoy, y quién es el dueño de cada dato a partir de ahora.'],
    ['Leads','Anuncios y formularios web entrando al CRM con su origen pegado.'],
    ['Cobros','Pasarelas y extractos del banco cuadrados contra el expediente.'],
    ['Calendarios','Reservas escritas en un calendario de verdad, no en una lista que alguien copia.'],
    ['Hojas de cálculo','Leídas donde el equipo aún las usa, sin obligar a migrar el primer día.'],
    ['Mensajería','WhatsApp y Telegram como el canal que una persona ya lee.'],
    ['Fallos','Cada ejecución registrada; una llamada que falla llega a una persona.'],
  ],
  'caso'=>[
    'img'=>'work-sumba.jpg','alt'=>'Integraciones en producción',
    'titulo'=>'Leads, cobros y calendarios que nadie vuelve a teclear',
    'texto'=>'En los proyectos que llevamos: los formularios de Meta entran solos en el CRM de una promotora con su campaña pegada; el bot de un operador turístico escribe las reservas en Google Calendar y manda enlaces de pago de Stripe; las reservas de una empresa de alquiler se cobran con su pasarela local; y las aprobaciones le llegan al dueño como un sí o un no en Telegram, y es la base de datos la que hace el cambio.',
    'cifras'=>[['0','leads tecleados a mano'],['1','dueño por dato'],['1','persona avisada si algo falla']],
  ],
  'faq'=>[
    ['¿Podéis conectar un programa que no tiene API?','A veces: por sus exportaciones, por sus avisos por correo o por una hoja de cálculo en la que escribe. Antes de hacerlo te decimos con franqueza lo frágil que es.'],
    ['¿Esto es lo mismo que Zapier?','Zapier va bien para unir dos servicios que ya traen botones el uno para el otro. Ven a nosotros cuando los datos necesitan reglas, cuando hay que guardar estado o cuando fallar en silencio no es aceptable.'],
    ['¿Tenemos que pasarnos todos a un sistema nuevo?','No. Casi siempre leemos los datos donde ya están y solo movemos lo que tiene un motivo para moverse.'],
    ['¿De quién son las credenciales?','Tuyas. Las cuentas son tuyas; a nosotros se nos da acceso y se puede retirar.'],
    ['¿Cuánto cuesta?','Cada proyecto se presupuesta por su alcance. Dinos qué herramientas usáis y dónde hay alguien tecleando dos veces.'],
  ],
  'asunto'=>'Integraciones y datos — /es/servicios/integraciones-y-datos',
],

'diseno-y-desarrollo-web' => [
  'lang'=>'es','url'=>'/es/servicios/diseno-y-desarrollo-web','codigo'=>'B07','eje'=>'BUILD',
  'title'=>'Diseño y desarrollo web a medida, sin plantillas — AxisWorks',
  'desc'=>'Webs diseñadas y programadas por las mismas dos personas: sin plantilla ni maquetador, rápidas en el móvil, en varios idiomas y conectadas con lo que pasa después de la consulta.',
  'eyebrow'=>'HOJA B07 — BUILD',
  'h1'=>'Diseño y desarrollo web a medida',
  'lead'=>'La web es el único software que tu cliente ve antes de hablar contigo. Tiene que cargar antes de que pierda el interés, y saber qué hacer con él después.',
  'spec'=>[
    'Diseñamos y programamos con las mismas manos, así que no se pierde nada entre la maqueta y la página. Sin plantilla y sin maquetador: la web se escribe para el negocio, por eso carga rápido en un móvil normal y por eso cambiar un precio no obliga a pelearse con un tema.',
    'Lo que casi todas las webs dejan fuera es <b>lo que pasa después del clic</b>. Un formulario que manda un correo a una bandeja que nadie mira no es un sistema de captación. Los nuestros pasan la consulta al CRM, al bot o al calendario, con la página de la que vino pegada.',
    'Y el contenido tiene una sola fuente. Si un precio o una fecha salen en la portada, en una guía y en la calculadora de reservas, se leen de un solo sitio: una web que da dos precios distintos para lo mismo pierde al cliente y, a veces, una reclamación.',
  ],
  'scope'=>[
    ['Diseño','Dirección de arte para el negocio, no un tema con el logo cambiado.'],
    ['Desarrollo','Programada a mano, ligera y rápida en el móvil.'],
    ['Contenido','Editable por vosotros desde un panel, con una fuente para cada precio y cada fecha.'],
    ['Idiomas','Versiones de verdad, cada una con su propia dirección para los buscadores.'],
    ['Base SEO','Títulos, datos estructurados, sitemap y los archivos que leen los asistentes de IA.'],
    ['Consultas','Conectadas al CRM, al bot o al calendario, no a una bandeja.'],
    ['Legal','Privacidad, aviso legal y cookies escritos para esa web, no copiados.'],
  ],
  'caso'=>[
    'img'=>'work-balimoto.jpg','alt'=>'Web de un operador turístico en producción',
    'titulo'=>'Dos webs en producción que venden',
    'texto'=>'Un operador de rutas en moto con calculadora de precio, páginas guía y pago de la reserva, cuyo contenido edita el propio cliente desde un panel; y una web de alquiler con entrega en el aeropuerto. Las dos están en producción y las dos pasan sus consultas a un bot de WhatsApp en vez de a una bandeja; en la del operador, cada precio —tarjetas, guías, calculadora— sale de una sola fuente que edita el cliente.',
    'cifras'=>[['2','webs en producción'],['1','panel para editar el contenido'],['0','plantillas o maquetadores']],
  ],
  'faq'=>[
    ['¿Por qué no WordPress o Wix?','Si una plantilla te sirve, es más barata y deberías usarla. Merecemos la pena cuando la web tiene que hacer algo —presupuestar, reservar, cobrar una señal, alimentar un CRM— o cuando la velocidad en el móvil pesa en la venta.'],
    ['¿Podemos editar el contenido nosotros?','Sí. Precios, textos y fotos se cambian desde un panel; no nos necesitas para mover una fecha.'],
    ['¿Hacéis los textos y las fotos?','Los textos, sí. Fotos y vídeo dependen de lo que haya; si no hay, te lo decimos en vez de rellenar con fotos de banco.'],
    ['¿Dónde se aloja?','En un alojamiento a tu nombre siempre que se pueda. El dominio es siempre tuyo.'],
    ['¿Cuánto cuesta?','Se presupuesta por alcance, y lo que mueve el precio es cuánto tiene que hacer la web después de que llega la visita. Lo explicamos en <a href="/es/cuanto-cuesta-un-software-a-medida">cuánto cuesta un software a medida</a>.'],
  ],
  'asunto'=>'Diseño y desarrollo web — /es/servicios/diseno-y-desarrollo-web',
],

'seo-y-sem' => [
  'lang'=>'es','url'=>'/es/servicios/seo-y-sem','codigo'=>'G02','eje'=>'GROW',
  'title'=>'SEO, SEM y posicionamiento en buscadores de IA — AxisWorks',
  'desc'=>'SEO técnico desde el primer día, SEM donde compensa y los archivos que leen ChatGPT y compañía, sin prometer posiciones que nadie puede prometer.',
  'eyebrow'=>'HOJA G02 — GROW',
  'h1'=>'SEO, SEM y buscadores de IA',
  'lead'=>'Nadie puede prometerte la primera posición. Lo que sí se puede prometer es que nada de tu propia web se lo esté impidiendo.',
  'spec'=>[
    'La mayor parte del SEO que hacemos ocurre en el código, y por eso quien construye la web está bien situado para hacerlo: direcciones limpias, una página por intención de búsqueda, versiones de idioma que se señalan entre sí, datos estructurados que dicen qué es el negocio y una web que carga rápido en el móvil. Nada de eso es un truco, y todo es fácil de hacer mal.',
    'Los buscadores tienen ahora un tercer público. Asistentes como ChatGPT, Claude o Perplexity responden sobre empresas leyendo sus webs. Publicamos lo que leen —un <code>llms.txt</code> generado del mismo catálogo que las páginas, y los rastreadores permitidos a propósito—, para que lo que cuentan de ti lo hayas escrito tú.',
    'El SEM, la búsqueda de pago, es la disciplina contraria: compra la visita hoy. Lo llevamos donde los números lo justifican y conectado al CRM, para que el informe hable de consultas y ventas y no de clics. Y si no compensa, te lo decimos claro.',
  ],
  'scope'=>[
    ['Auditoría','Qué impide hoy que tu web se lea bien: velocidad, estructura, duplicados, señales rotas.'],
    ['Estructura','Una dirección por intención, en cada idioma, con su par declarado.'],
    ['Datos estructurados','Organización, servicios, preguntas frecuentes y migas, generados de la propia página.'],
    ['Palabras clave','Desde tu Search Console, tus leads y la página de resultados real, no desde un volumen inventado.'],
    ['Buscadores de IA','<code>llms.txt</code>, permisos de rastreo y contenido escrito para ser citado.'],
    ['SEM','Búsqueda de pago donde compensa, atada al CRM.'],
    ['Medición','Search Console y analítica instaladas antes de juzgar nada.'],
  ],
  'caso'=>[
    'img'=>'work-balimoto.jpg','alt'=>'Estructura de búsqueda en una web en producción',
    'titulo'=>'Esta web, y las que llevamos',
    'texto'=>'axisworks.studio es el ejemplo: páginas en español e inglés emparejadas con hreflang, una hoja por servicio, un sitemap y un <code>llms.txt</code> que salen del mismo catálogo que las páginas, y las direcciones nuevas enviadas por IndexNow al publicarse. Las webs de clientes en producción llevan la misma base, con páginas guía escritas para lo que sus clientes teclean de verdad.',
    'cifras'=>[['2','idiomas, cada uno con sus direcciones'],['1','catálogo para páginas, sitemap y llms.txt'],['0','posiciones prometidas']],
  ],
  'faq'=>[
    ['¿Nos ponéis los primeros en Google?','Nadie honesto puede prometer eso. Podemos quitar lo que te frena, hacer páginas para lo que buscan tus clientes y después medirlo.'],
    ['¿Cuándo se ven resultados?','El SEO se mide en meses, no en semanas. El SEM empieza el día que se enciende, y cuesta en consecuencia.'],
    ['¿Qué es posicionar en buscadores de IA?','Que asistentes como ChatGPT o Perplexity encuentren una descripción clara y correcta de tu negocio cuando leen tu web, y que tengan permiso para leerla.'],
    ['¿Escribís los contenidos?','Sí, en español e inglés, para la persona que busca y sin rellenar de palabras clave.'],
    ['¿Hace falta una web nueva?','No siempre. Si la actual se puede arreglar, la arreglamos. Si lo que frena es la plataforma, te lo diremos.'],
  ],
  'asunto'=>'SEO y SEM — /es/servicios/seo-y-sem',
],

'redes-sociales-y-contenido' => [
  'lang'=>'es','url'=>'/es/servicios/redes-sociales-y-contenido','codigo'=>'G03','eje'=>'GROW',
  'title'=>'Gestión de redes sociales y contenido para empresas — AxisWorks',
  'desc'=>'Un plan de contenido por cuenta, piezas hechas para el móvil en el que se ven y una voz que es de la marca, planificado a partir de lo que ya funciona en tu sector.',
  'eyebrow'=>'HOJA G03 — GROW',
  'h1'=>'Redes sociales y contenido para empresas',
  'lead'=>'Una cuenta que publica cada día y no dice nada sale más cara que una que publica dos veces por semana y merece la pena seguir.',
  'spec'=>[
    'Empezamos por la cuenta, no por el calendario. Un grupo con varias marcas no necesita el mismo feed tres veces: cada cuenta tiene un trabajo —confianza, prueba o deseo— y cada pieza va a la cuenta cuyo trabajo hace.',
    'Después miramos qué funciona ya en el sector antes de escribir nada. En un plan, las referencias que mejor rendían tenían el mismo patrón: delante de la cámara salía quien tiene las manos en el trabajo —el constructor, el notario—, no el fundador, y los temas que ganaban eran de riesgo, no de belleza. Eso cambió quién graba y qué graba.',
    'El contenido orgánico es además lo que abarata la publicidad, y por eso esta hoja va al lado de la <a href="/es/servicios/meta-ads">G01</a>. Aplica la misma disciplina: casi todo se ve a tamaño miniatura en un móvil, y se hace para eso.',
  ],
  'scope'=>[
    ['Estrategia','Un trabajo por cuenta, y una regla para saber qué pieza va dónde.'],
    ['Referencias','Lo que ya funciona en tu sector, medido antes de copiar nada.'],
    ['Plan','Un calendario atado a lo que el negocio vende ese mes.'],
    ['Producción','Vídeo vertical, carruseles y textos hechos para el móvil.'],
    ['Voz','Escrita con las palabras de la marca, en cada idioma en el que habla.'],
    ['Comunidad','Comentarios y mensajes que llegan a la persona que puede contestarlos.'],
    ['Revisión','Qué hizo cada pieza, leído aparte de lo que hicieron los anuncios.'],
  ],
  'caso'=>[
    'img'=>'work-lawang.jpg','alt'=>'Plan de contenido para una promotora',
    'titulo'=>'Tres cuentas para una promotora',
    'texto'=>'Una marca matriz y dos proyectos, cada uno con su cuenta y su trabajo: la matriz da confianza con contenido técnico y legal, un proyecto enseña la obra avanzando y el otro vende el lugar. El plan salió de treinta y dos referencias del sector y de auditar el material que ya existía, que resultó ser mucho menos de lo que parecía: grabar no era opcional.',
    'cifras'=>[['3','cuentas, tres trabajos distintos'],['32','referencias del sector analizadas'],['1','voz por cuenta']],
  ],
  'faq'=>[
    ['¿Publicáis vosotros?','Sí, o le pasamos el plan y las piezas a tu equipo, como prefieras.'],
    ['¿Grabáis?','Planificamos qué grabar y lo editamos. La grabación se hace contigo o con un equipo local, porque el mejor material es el real.'],
    ['¿Garantizáis seguidores?','No. Los seguidores que se compran no valen nada. Planificamos para consultas y confianza.'],
    ['¿En qué se diferencia de los anuncios?','Los anuncios compran alcance hoy; el contenido es lo que la gente encuentra cuando te investiga. Cada uno abarata al otro, por eso hacemos los dos.'],
    ['¿Cuánto cuesta?','Se presupuesta por alcance: número de cuentas, piezas al mes y si hay grabación.'],
  ],
  'asunto'=>'Redes y contenido — /es/servicios/redes-sociales-y-contenido',
],

'gestion-marca-y-rumbo' => [
  'lang'=>'es','url'=>'/es/servicios/gestion-marca-y-rumbo','codigo'=>'A01','eje'=>'ADVISORY',
  'title'=>'Gestión, identidad de marca y dirección para pymes — AxisWorks',
  'desc'=>'Un estudio al lado del dueño: identidad de marca, cómo se organiza la empresa y qué construir primero, decidido con datos y escrito para que no se pierda.',
  'eyebrow'=>'HOJA A01 — ADVISORY',
  'h1'=>'Gestión, marca y rumbo',
  'lead'=>'Casi todo lo que construimos sale mejor cuando alguien ha decidido antes qué es el negocio, cómo se organiza y qué importa este trimestre. Eso es esta hoja.',
  'spec'=>[
    'Es el trabajo que cruza los dos ejes. Antes de un CRM hay un proceso de venta; antes de una campaña hay una marca; antes de una suite interna hay una organización que decide quién hace qué. Cuando eso no está claro, el software acaba decidiéndolo por accidente.',
    'Nos sentamos al lado del dueño y hacemos tres cosas. <b>Marca</b>: identidad, voz y las reglas que la mantienen igual en la web, en los documentos y en las cuentas. <b>Organización</b>: quién es dueño de cada proceso y de cada dato, por escrito. <b>Rumbo</b>: qué construir o arreglar primero, elegido por lo que más cuesta hoy.',
    'Todo lo que decidimos queda escrito con su motivo y su fecha, para que la siguiente persona —o nosotros mismos dentro de un año— sepa por qué se decidió y si sigue valiendo. Una decisión que solo vive en una reunión desaparece a la semana siguiente.',
  ],
  'scope'=>[
    ['Identidad de marca','Nombre, logo, paleta, tipografía y voz, con las reglas que las mantienen coherentes.'],
    ['Organización','Quién es dueño de cada proceso y de cada dato.'],
    ['Prioridades','Qué construir o arreglar primero, ordenado por lo que cuesta dejarlo.'],
    ['Estructura de la oferta','Cómo se presenta lo que vendes; el precio nunca, que es tuyo.'],
    ['Registro de decisiones','Cada decisión escrita con su motivo y su fecha.'],
    ['Revisión','Mirar los números cada cierto tiempo contra lo que dijimos que haríamos.'],
    ['Traspaso','Todo documentado para que no dependa de nosotros.'],
  ],
  'caso'=>[
    'img'=>'work-lawang.jpg','alt'=>'Marca y rumbo para una promotora',
    'titulo'=>'Una promotora, de la marca a la operación',
    'texto'=>'Para una promotora definimos la identidad de la marca matriz y el trabajo de cada una de sus cuentas, y decidimos con el dueño qué construye después su suite interna. Cada decisión queda escrita con su motivo y su fecha, y eso es lo que permite que dos personas y un equipo de departamentos de IA la lleven sin perder el hilo.',
    'cifras'=>[['1','sistema de marca en web, documentos y cuentas'],['11','herramientas internas bajo un menú'],['1','registro de decisiones, fechado']],
  ],
  'faq'=>[
    ['¿Esto es consultoría?','En parte, pero además construimos lo que recomendamos. Eso mantiene honesto el consejo: nos toca vivir con él.'],
    ['¿Nos ponéis los precios?','No. Podemos estructurar cómo se presenta la oferta; el precio es siempre decisión del dueño.'],
    ['¿Podemos contratar solo la marca?','Sí. Es la forma más habitual de empezar con esta hoja.'],
    ['¿Cada cuánto nos vemos?','Tanto como se mueva el negocio: normalmente una revisión fija, y además cuando una decisión no puede esperar.'],
    ['¿Cuánto cuesta?','Se presupuesta por alcance. Cuéntanos qué no está claro hoy y te decimos por dónde empezaríamos.'],
  ],
  'asunto'=>'Gestión, marca y rumbo — /es/servicios/gestion-marca-y-rumbo',
],

];
