<?php
/* Textos de la portada nueva y de Agents as a Service (10-oct-2026), EN y ES en un solo fichero.
 * Solo hechos que se pueden defender (fuentes: contexto/pilotos.md, contexto/erp_tipos.md,
 * departamentos/pilotos/prompt.md). Nada de clientes de otros proyectos ni cifras inventadas.
 * El estudio (direcciones, departamentos, autónomos) sale de home_textos.php + organigrama.php.
 * Toda clave nueva entra en las DOS columnas. {N}/{PALABRA} se cuentan del organigrama. */
define('ERP_URL', 'https://erp.axisworks.studio/');
define('AAAS_EN', '/agents-as-a-service');
define('AAAS_ES', '/es/agentes-como-servicio');
define('ACT_EN', '/studio-activity');
define('ACT_ES', '/es/actividad-del-estudio');

$LAND = [
'en' => [
  'nav_products'=>'Products','nav_agents'=>'Agents','nav_tools'=>'Tools','nav_erp'=>'ERP demo','nav_cta'=>'Talk to the studio',
  'skip'=>'Skip to content',
  'h_eyebrow'=>'Software studio with an AI team',
  'h_h1'=>'Software built by AI departments, <em>signed off by people.</em>',
  'h_sub'=>'{PALABRA_CAP} AI departments design, build and run software for businesses. Javier and Andrea direct the work and approve every decision that matters.',
  'h_cta1'=>'See what we sell','h_cta2'=>'Open the ERP demo',
  'h_tag'=>'Illustration · sample data, not live activity',
  'h_act'=>'See the real record (published with a delay)',
  'k_dep'=>'Departments','k_act'=>'Active at once','k_coord'=>'Coordinations','k_st'=>'Data','k_st_v'=>'Sample',
  'leg'=>['Decides · gate','Review the plan','Spawned subagents','Products','Build and create','Publish','Input · output','Human oversight'],
  'p_eyebrow'=>'What we sell','p_h2'=>'An ERP, the agents that work on it, and websites.',
  'p_lead'=>'You run the business in the ERP. The agents (in testing) work on its data, and the websites bring customers to it.',
  'erp_chip'=>'Demo available','erp_h3'=>'AxisWorks ERP',
  'erp_p'=>'A modular ERP: you switch on the modules your business uses today and add others when it needs them.',
  'erp_types'=>['Properties','Bookings','Services'],
  'erp_b'=>['Contracts, invoices and payments in one system','One codebase for every client, one private database per client'],
  'erp_pl'=>'Planned: landing pages generated from your ERP data','erp_more'=>'Open the demo',
  'ag_chip'=>'In testing · shadow mode','ag_h3'=>'Agents as a Service',
  'ag_p'=>'A pilot agent that runs the day-to-day of a business inside hard limits you set. Each business gets its own pack of nine agents.',
  'ag_nine'=>'Nine agents per business',
  'ag_b'=>['Hard stops: price, publishing, deleting, spending and anything sent to a third party are reserved for a person by default','Operates on your ERP data'],
  'ag_pl'=>'Planned: access to our AI Tools (video, carousels, research, plot maps)','ag_more'=>'See how it works',
  'wb_chip'=>'In production','wb_h3'=>'Websites &amp; landing pages',
  'wb_p'=>'Custom websites, designed, built, published and tested by the same team.',
  'wb_b'=>['SEO and Meta Ads from the same studio','A separate department tests it in production before we call it done'],
  'wb_pl'=>'Planned: landings built from the information in your ERP','wb_more'=>'Talk to the studio',
  'flow'=>['AaaS','operates on','ERP','landings (planned)','Websites'],
  'c_h2'=>'Want to see it working with your business?',
  'c_p'=>'Tell us about your business and we will show you the ERP, the agents and the website we would build around it.',
  'c_erp'=>'Open the ERP demo',
  'f_blurb'=>'Business software, bots and automation, built to order.',
  'f_blurb2'=>'A two-person studio with a team of AI departments behind it. We work in English and Spanish.',
  'f_trade'=>'© 2026 AXISWORKS · PT MAHKOTA PROPERTY GLOBAL',
],
'es' => [
  'nav_products'=>'Productos','nav_agents'=>'Agentes','nav_tools'=>'Herramientas','nav_erp'=>'Demo del ERP','nav_cta'=>'Hablar con el estudio',
  'skip'=>'Saltar al contenido',
  'h_eyebrow'=>'Estudio de software con equipo de IA',
  'h_h1'=>'Software hecho por departamentos de IA, <em>con el visto bueno de personas.</em>',
  'h_sub'=>'{PALABRA_CAP} departamentos de IA diseñan, construyen y mantienen software para empresas. Javier y Andrea dirigen el trabajo y aprueban cada decisión que importa.',
  'h_cta1'=>'Ver lo que vendemos','h_cta2'=>'Abrir la demo del ERP',
  'h_tag'=>'Ilustración · datos de ejemplo, no actividad en vivo',
  'h_act'=>'Ver el registro real (se publica con retraso)',
  'k_dep'=>'Departamentos','k_act'=>'Activos a la vez','k_coord'=>'Coordinaciones','k_st'=>'Datos','k_st_v'=>'Ejemplo',
  'leg'=>['Decide · puerta','Opinan sobre el plan','Subagentes que se levantan','Productos','Construyen y crean','Publican','Entrada · salida','Supervisión humana'],
  'p_eyebrow'=>'Lo que vendemos','p_h2'=>'Un ERP, los agentes que trabajan sobre él y webs.',
  'p_lead'=>'El negocio se lleva en el ERP. Los agentes (en pruebas) trabajan sobre sus datos y las webs le traen clientes.',
  'erp_chip'=>'Demo disponible','erp_h3'=>'AxisWorks ERP',
  'erp_p'=>'Un ERP por módulos: enciendes los que tu negocio usa hoy y añades otros cuando los necesite.',
  'erp_types'=>['Propiedades','Reservas','Servicios'],
  'erp_b'=>['Contratos, facturas y cobros en un solo sistema','Un mismo código para todos los clientes, una base de datos privada por cliente'],
  'erp_pl'=>'Previsto: landings generadas con los datos de tu ERP','erp_more'=>'Abrir la demo',
  'ag_chip'=>'En pruebas · modo sombra','ag_h3'=>'Agentes como servicio',
  'ag_p'=>'Un agente piloto que lleva el día a día de un negocio dentro de los límites duros que tú fijas. Cada negocio tiene su propio pack de nueve agentes.',
  'ag_nine'=>'Nueve agentes por negocio',
  'ag_b'=>['Paradas duras: precio, publicar, borrar, gastar y todo envío a un tercero quedan, por defecto, reservados a una persona','Opera sobre los datos de tu ERP'],
  'ag_pl'=>'Previsto: acceso a nuestras AI Tools (vídeo, carruseles, investigación, mapas de parcelas)','ag_more'=>'Ver cómo funciona',
  'wb_chip'=>'En producción','wb_h3'=>'Webs y landings',
  'wb_p'=>'Webs a medida que diseña, construye, publica y prueba el mismo equipo.',
  'wb_b'=>['SEO y Meta Ads desde el mismo estudio','Un departamento aparte la prueba en producción antes de darla por terminada'],
  'wb_pl'=>'Previsto: landings construidas con la información de tu ERP','wb_more'=>'Hablar con el estudio',
  'flow'=>['AaaS','opera sobre','ERP','landings (previsto)','Webs'],
  'c_h2'=>'¿Lo vemos funcionando con tu negocio?',
  'c_p'=>'Cuéntanos a qué se dedica tu negocio y te enseñamos el ERP, los agentes y la web que montaríamos alrededor.',
  'c_erp'=>'Abrir la demo del ERP',
  'f_blurb'=>'Software de gestión, bots y automatización, hechos a medida.',
  'f_blurb2'=>'Un estudio de dos personas con un equipo de departamentos de IA detrás. Trabajamos en español e inglés.',
  'f_trade'=>'© 2026 AXISWORKS · PT MAHKOTA PROPERTY GLOBAL',
],
];

/* Los nueve agentes del pack (contexto/pilotos.md §6, «Nombres internos», 1-oct-2026).
 * [nombre, rol, qué hace]. Son ROLES, no un estado de construcción: el estado va aparte. */
$AGENTES = [
'en' => [
  ['Captain','CEO of the business','Sets the plan, decides who works on what and is the only voice towards the business owner.'],
  ['Reception','Customer service','Answers customers. The first message of every conversation says it is an AI and how to reach a person.'],
  ['Radar','Market &amp; strategy','Reads the market and proposes where to bet. Read-only: it changes nothing.'],
  ['Figures','Analytics','Measures what each bet delivers and reports the numbers.'],
  ['Hook','Acquisition','Finds new customers within the budget and the channels the owner allows.'],
  ['Quill','Creative &amp; conversion','Writes the content and the pages that turn a visit into a sale.'],
  ['Listener','Customer analysis','Reads what customers say to find what they want and what annoys them.'],
  ['Route','Operations','Looks after day-to-day operations. Off where the business has none.'],
  ['Treasurer','Money rules','Plain code, not a language model: enforces the monthly spending cap and stops spending when it is reached.'],
],
'es' => [
  ['Capitán','CEO del negocio','Fija el plan, decide quién trabaja en qué y es la única voz hacia el dueño del negocio.'],
  ['Recepción','Atención al cliente','Atiende a los clientes. El primer mensaje de cada conversación dice que es una IA y cómo hablar con una persona.'],
  ['Radar','Mercado y estrategia','Lee el mercado y propone dónde apostar. Solo lectura: no cambia nada.'],
  ['Cifras','Analítica','Mide lo que da cada apuesta e informa de los números.'],
  ['Gancho','Captación','Busca clientes nuevos dentro del presupuesto y los canales que el dueño permite.'],
  ['Pluma','Creatividad y conversión','Escribe el contenido y las páginas que convierten una visita en venta.'],
  ['Oído','Análisis de clientes','Lee lo que dicen los clientes para saber qué quieren y qué les molesta.'],
  ['Ruta','Operaciones','Cuida la operación del día a día. Apagado donde el negocio no tiene operación.'],
  ['Tesorero','Reglas del dinero','Código normal, no un modelo de lenguaje: hace cumplir el tope mensual de gasto y corta el gasto al llegar a él.'],
],
];

$AAAS = [
'en' => [
  'title'=>'Agents as a Service — AI agents that run a business | AxisWorks',
  'desc'=>'Nine AI agents per business, working on your ERP data within hard limits: price, publishing, deleting, spending and anything sent to a third party stay with a person. In testing, shadow mode.',
  'eyebrow'=>'Agents as a Service',
  'h1'=>'An agent that runs your business, <em>within limits a person sets.</em>',
  'sub'=>'A pilot takes on customer service, pricing, content, lead generation and the watching of the money. Every consequential decision stays with a person unless the owner has granted an exception in writing.',
  'cta1'=>'Talk to the studio','cta2'=>'Meet the nine agents',
  'st_chip'=>'In testing · shadow mode',
  'st_p'=>'In shadow mode the pilot decides but does not execute. Today one pilot is being tested, on our own product, <a href="https://bodaenlace.com">BodaEnlace</a>. Two more businesses are planned. It is not yet a running service you can buy.',
  'ag_eyebrow'=>'The pack','ag_h2'=>'Nine agents for each business.',
  'ag_lead'=>'Each agent holds only the keys its job needs. The pack comes as one: a pilot does not leave shadow mode until all nine are ready, and the nine are still being completed in testing.',
  'ag_note'=>'The builder, the reviewer, the verifier and the approvals are mechanisms around the pack and do not count as agents.',
  'how_eyebrow'=>'How it works · by design','how_h2'=>'The agent proposes and a person approves.',
  'how'=>[
    ['The owner writes the brief','Mission, context, spending cap, permissions and which functions the agent may run. The agent can read this file and can never write it.'],
    ['The agent proposes bets','Every decision carries a hypothesis, a measure, a deadline and a cost. It proposes changes to the ERP; it does not make them.'],
    ['A person approves what matters','What touches a hard stop waits for a person. Everything the agent does is recorded in the business’s ERP, and anything not recorded there counts as not done.'],
    ['What works becomes routine','A bet that works becomes code that runs by itself; one that does not is dropped and kept as a lesson. After 14 days without progress it changes strategy; after two failed cycles it escalates to the owner with options.'],
  ],
  'lim_eyebrow'=>'Limits and guarantees','lim_h2'=>'Hard stops that are not up to the agent.',
  'lim_lead'=>'These five are reserved for a person by default. Any exception is granted in writing by the owner, for one pilot, and is not inherited by another.',
  'stops'=>['Price','Publishing','Deleting','Spending','Sending to a third party'],
  'lim'=>[
    ['block','Money and dismissal live in code','A monthly spending cap, set by the owner, is enforced by code, not by an agent. The agent spends what it is given each month, never more.'],
    ['visibility','It says it is an AI','The first message of every conversation says an AI is answering and how to reach a person.'],
    ['rule','It never invents proof','No made-up reviews, testimonials or figures. It does not promise anything outside its brief.'],
    ['fact_check','A closed list goes to a person','Identity checks, signatures, the first real charge, irreversible actions and new legal texts always escalate to the owner.'],
    ['verified_user','Its own brief is read-only','No tool of the agent reaches the file that sets its limits. Public email never reaches code, and the role that reads it has no tools.'],
    ['deployed_code','Everything leaves a trace','Activity, decisions, escalations and treasury are written to the business’s ERP so the owner can see them.'],
  ],
  'on_eyebrow'=>'What it runs on','on_h2'=>'It operates on your ERP data.',
  'on_p'=>'The agents work on the same records you do: customers, bookings, contracts, invoices. One agent module inside the ERP holds the brief, the audit trail, the proposals and the approvals.',
  'on_cta'=>'Open the ERP demo',
  'sx_eyebrow'=>'Status and what comes next','sx_h2'=>'Where it stands today.',
  'sx'=>[
    ['In testing now',['One pilot, on our own product, in shadow mode: it decides without executing.','The agent module inside the ERP.']],
    ['Being completed',['The rest of the nine-agent pack.','Two more businesses planned.']],
    ['Planned',['AI Tools for pilots: video styles, carousels, a researcher and plot maps.','Not available yet, and not for sale until it is.']],
  ],
  'cl_h2'=>'Want to know if an agent pack fits your business?',
  'cl_p'=>'Tell us about your business and we will tell you whether it could work for you, and when.',
  'jsonld_name'=>'Agents as a Service',
],
'es' => [
  'title'=>'Agentes como servicio — agentes de IA que llevan un negocio | AxisWorks',
  'desc'=>'Nueve agentes de IA por negocio, sobre los datos de tu ERP y dentro de límites duros: precio, publicar, borrar, gastar y cualquier envío a un tercero los decide una persona. En pruebas, modo sombra.',
  'eyebrow'=>'Agentes como servicio',
  'h1'=>'Un agente que lleva tu negocio, <em>dentro de los límites que fija una persona.</em>',
  'sub'=>'Un piloto se encarga de la atención al cliente, el precio, el contenido, la captación y la vigilancia del dinero. Toda decisión con consecuencias queda en manos de una persona, salvo una excepción que el dueño haya concedido por escrito.',
  'cta1'=>'Hablar con el estudio','cta2'=>'Conocer a los nueve agentes',
  'st_chip'=>'En pruebas · modo sombra',
  'st_p'=>'En modo sombra el piloto decide pero no ejecuta. Hoy se prueba un piloto, en un producto nuestro, <a href="https://bodaenlace.com">BodaEnlace</a>. Hay dos negocios más previstos. Todavía no es un servicio en marcha que se pueda contratar.',
  'ag_eyebrow'=>'El pack','ag_h2'=>'Nueve agentes para cada negocio.',
  'ag_lead'=>'Cada agente tiene solo las llaves que su trabajo necesita. El pack va entero: un piloto no sale del modo sombra hasta tener los nueve listos, y los nueve se están completando en pruebas.',
  'ag_note'=>'El constructor, el revisor, el verificador y las aprobaciones son mecanismos alrededor del pack y no cuentan como agentes.',
  'how_eyebrow'=>'Cómo funciona · por diseño','how_h2'=>'El agente propone y una persona aprueba.',
  'how'=>[
    ['El dueño escribe la ficha','Misión, contexto, tope de gasto, permisos y qué funciones puede llevar el agente. El agente puede leer esta ficha y nunca escribirla.'],
    ['El agente propone apuestas','Cada decisión lleva una hipótesis, una medida, un plazo y un coste. Propone cambios al ERP; no los hace.'],
    ['Una persona aprueba lo que importa','Lo que toca una parada dura espera a una persona. Todo lo que hace el agente queda registrado en el ERP del negocio, y lo que no consta ahí se da por no hecho.'],
    ['Lo que funciona pasa a rutina','Una apuesta que funciona se convierte en código que corre solo; la que no, se descarta y queda como lección. A los 14 días sin avance cambia de estrategia; tras dos ciclos fallidos escala al dueño con opciones.'],
  ],
  'lim_eyebrow'=>'Límites y garantías','lim_h2'=>'Paradas duras que no dependen del agente.',
  'lim_lead'=>'Estas cinco quedan, por defecto, reservadas a una persona. Cualquier excepción la concede el dueño por escrito, para un piloto, y no la hereda otro.',
  'stops'=>['Precio','Publicar','Borrar','Gastar','Enviar a un tercero'],
  'lim'=>[
    ['block','El dinero y el despido viven en código','Un tope mensual de gasto, fijado por el dueño, lo hace cumplir el código, no un agente. El agente gasta lo que se le da cada mes, nunca más.'],
    ['visibility','Dice que es una IA','El primer mensaje de cada conversación dice que responde una IA y cómo hablar con una persona.'],
    ['rule','Nunca inventa pruebas','Ni reseñas, ni testimonios, ni cifras inventadas. No promete nada fuera de su ficha.'],
    ['fact_check','Una lista cerrada va a una persona','Verificación de identidad, firmas, el primer cobro real, acciones irreversibles y textos legales nuevos escalan siempre al dueño.'],
    ['verified_user','Su propia ficha es de solo lectura','Ninguna herramienta del agente llega a la ficha que fija sus límites. El correo público nunca llega a código y el rol que lo lee no tiene herramientas.'],
    ['deployed_code','Todo deja rastro','Actividad, decisiones, escalados y tesorería se escriben en el ERP del negocio para que el dueño los vea.'],
  ],
  'on_eyebrow'=>'Sobre qué corre','on_h2'=>'Opera sobre los datos de tu ERP.',
  'on_p'=>'Los agentes trabajan sobre los mismos registros que tú: clientes, reservas, contratos, facturas. Un módulo de agente dentro del ERP guarda la ficha, el rastro de auditoría, las propuestas y las aprobaciones.',
  'on_cta'=>'Abrir la demo del ERP',
  'sx_eyebrow'=>'Estado y lo que viene','sx_h2'=>'Dónde está hoy.',
  'sx'=>[
    ['En pruebas ahora',['Un piloto, en un producto nuestro, en modo sombra: decide sin ejecutar.','El módulo de agente dentro del ERP.']],
    ['Completándose',['El resto del pack de nueve agentes.','Dos negocios más previstos.']],
    ['Previsto',['AI Tools para los pilotos: estilos de vídeo, carruseles, un investigador y mapas de parcelas.','Todavía no disponible, y no se vende hasta que lo esté.']],
  ],
  'cl_h2'=>'¿Quieres saber si un pack de agentes encaja en tu negocio?',
  'cl_p'=>'Cuéntanos a qué se dedica tu negocio y te diremos si podría funcionar para ti y cuándo.',
  'jsonld_name'=>'Agentes como servicio',
],
];
