<?php
/* GENERADO por tools/organigrama_web.py (repo de la agencia) desde la ficha pública de
 * cada departamentos/<d>/prompt.md. NO EDITAR A MANO: se regenera en el cierre de turno
 * y `python tools/organigrama_web.py --check` falla si diverge. Para cambiar un texto,
 * cambia la ficha. La frase de cada sección (BUILD…) es copy y vive en home_textos.php. */

$ORGANIGRAMA = [
  'n' => 14,
  'palabra' => ['en' => 'fourteen', 'es' => 'catorce'],
  'deps' => [
    ['seccion' => 'BUILD', 'cara' => 'dev', 'imagen' => true,
      'en' => ['Development', 'writes the code', ['B01', 'B02', 'B05', 'B07']],
      'es' => ['Desarrollo', 'escribe el código', ['B01', 'B02', 'B05', 'B07']],
    ],
    ['seccion' => 'BUILD', 'cara' => 'data', 'imagen' => true,
      'en' => ['Data', 'integrations &amp; APIs', ['B06']],
      'es' => ['Datos', 'integraciones y APIs', ['B06']],
    ],
    ['seccion' => 'BUILD', 'cara' => 'bots', 'imagen' => true,
      'en' => ['Bots', 'WhatsApp engine', ['B03', 'B04']],
      'es' => ['Bots', 'motor de WhatsApp', ['B03', 'B04']],
    ],
    ['seccion' => 'BUILD', 'cara' => 'arch', 'imagen' => true,
      'en' => ['Architecture', '3D house models', ['3D models of homes for sale, from the client&rsquo;s plans']],
      'es' => ['Arquitectura', 'viviendas en 3D', ['Modelos 3D de viviendas en venta, a partir de los planos del cliente']],
    ],
    ['seccion' => 'BUILD', 'cara' => 'deploy', 'imagen' => true,
      'en' => ['Deploy', 'ships &amp; verifies', ['Hosting, go-live and checks in production']],
      'es' => ['Deploy', 'publica y verifica', ['Alojamiento, puesta en marcha y comprobación en producción']],
    ],
    ['seccion' => 'BUILD', 'cara' => 'games', 'imagen' => false,
      'en' => ['Games', 'engine &amp; game', ['A game engine and the game built on it']],
      'es' => ['Videojuegos', 'motor y juego', ['Un motor de juego y el juego que corre sobre él']],
    ],
    ['seccion' => 'GROW', 'cara' => 'design', 'imagen' => true,
      'en' => ['Design', 'art direction', ['Brand identity', 'Interface design for every product']],
      'es' => ['Diseño', 'dirección de arte', ['Identidad de marca', 'Diseño de interfaz de cada producto']],
    ],
    ['seccion' => 'GROW', 'cara' => 'marketing', 'imagen' => true,
      'en' => ['Marketing', 'Meta Ads &amp; SEO', ['G01', 'G02', 'G03']],
      'es' => ['Marketing', 'Meta Ads y SEO', ['G01', 'G02', 'G03']],
    ],
    ['seccion' => 'GROW', 'cara' => 'comms', 'imagen' => true,
      'en' => ['Comms', 'press &amp; media', ['Press releases and press kits']],
      'es' => ['Comunicación', 'prensa y medios', ['Notas y kits de prensa']],
    ],
    ['seccion' => 'CONTROL', 'cara' => 'security', 'imagen' => true,
      'en' => ['Security', 'audits &amp; secrets', ['Security audits', 'Secrets and incident response']],
      'es' => ['Seguridad', 'auditorías y secretos', ['Auditorías de seguridad', 'Secretos y respuesta a incidentes']],
    ],
    ['seccion' => 'CONTROL', 'cara' => 'legal', 'imagen' => true,
      'en' => ['Legal', 'contracts &amp; policies', ['Client contracts', 'Privacy, terms and cookies']],
      'es' => ['Legal', 'contratos y políticas', ['Contratos con clientes', 'Privacidad, términos y cookies']],
    ],
    ['seccion' => 'CONTROL', 'cara' => 'admin', 'imagen' => true,
      'en' => ['Admin', 'billing &amp; tax', ['Invoicing and tax filings']],
      'es' => ['Administración', 'facturación y fiscalidad', ['Facturación y modelos fiscales']],
    ],
    ['seccion' => 'CONTROL', 'cara' => 'docs', 'imagen' => true,
      'en' => ['Docs', 'proposals &amp; reports', ['Proposals, reports and handovers']],
      'es' => ['Documentación', 'propuestas e informes', ['Propuestas, informes y entregas']],
    ],
    ['seccion' => 'CONTROL', 'cara' => 'org', 'imagen' => true,
      'en' => ['Organisation', 'runs the studio itself', ['The studio&rsquo;s own structure: departments and rules']],
      'es' => ['Organización', 'la estructura del estudio', ['La estructura del propio estudio: departamentos y reglas']],
    ],
  ],
];
